version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - database
      - redis
    links:
      - redis
    command: >
       bash ./start_project.sh
    volumes:
      - .:/bookkeeping_web/
      - static:/bookkeeping_web/static/
    environment:
      - .env

  database:
    image: postgres 
    restart: always
    environment:
      - POSTGRES_DB=bookkeeping
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=18960707
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  celery:
    restart: always
    build: 
      context: .
    command: celery -A conf worker --loglevel=info
    depends_on:
      - redis
      - app
      
  nginx: 
    build: ./nginx
    volumes:
      - static:/bookkeeping_web/static
    depends_on:
      - app
    ports:
      - 80:80
volumes:
  static:
  database-data:
