# Generated by Django 4.2.4 on 2023-08-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userexpenses',
            options={'verbose_name': 'Расход пользователя', 'verbose_name_plural': 'Расходы пользователя'},
        ),
        migrations.AlterModelOptions(
            name='userincomes',
            options={'verbose_name': 'Доходы пользователя', 'verbose_name_plural': 'Доходы Пользователя'},
        ),
        migrations.AlterModelOptions(
            name='usertransfertoaccount',
            options={'verbose_name': 'Перевод Пользователя', 'verbose_name_plural': 'Перевод Пользователя'},
        ),
        migrations.AddField(
            model_name='userexpenses',
            name='comment',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='userincomes',
            name='comment',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='userexpenses',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_expenses', to='bookkeeping_site.categoryincome', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='userincomes',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_incomes', to='bookkeeping_site.categoryincome', verbose_name='Подкатегория'),
        ),
    ]
