# Generated by Django 4.2.4 on 2023-09-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorycurrency',
            name='course',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='course',
        ),
    ]
