# Generated by Django 4.2.4 on 2023-08-16 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryexpenses',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='bookkeeping_site.categoryexpenses', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='categoryincome',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='bookkeeping_site.categoryincome', verbose_name='Категория'),
        ),
    ]
