# Generated by Django 4.2.4 on 2023-09-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping_site', '0002_remove_categorycurrency_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycurrency',
            name='course',
            field=models.FloatField(default=0, verbose_name='Курс'),
        ),
    ]
