# Generated by Django 4.2.4 on 2023-08-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping_site', '0002_categoryexpenses_parent_categoryincome_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория Счета',
                'verbose_name_plural': 'Категории Счетов',
            },
        ),
    ]
