# Generated by Django 4.2.4 on 2023-09-24 16:59

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping_site', '0002_rename_userdebt_userdebts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.fields.related.OneToOneField, to='bookkeeping_site.categoryaccounts', verbose_name='Cчета'),
        ),
    ]
