# Generated by Django 4.2.4 on 2023-08-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping_site', '0002_alter_userexpenses_options_alter_userincomes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpenses',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userexpenses',
            name='created_at',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='userincomes',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userincomes',
            name='created_at',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
