# Generated by Django 4.2.4 on 2023-08-19 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookkeeping_site', '0003_categoryaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название категории валюты')),
            ],
            options={
                'verbose_name': 'Категория Валюты',
                'verbose_name_plural': 'Категории Валют',
            },
        ),
        migrations.AlterField(
            model_name='categoryaccounts',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название категории счета'),
        ),
        migrations.AlterField(
            model_name='categoryexpenses',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название категории расхода'),
        ),
        migrations.AlterField(
            model_name='categoryincome',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название категории дохода'),
        ),
        migrations.CreateModel(
            name='UserExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Дата')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping_site.categoryaccounts', verbose_name='Счет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping_site.categoryexpenses', verbose_name='Категория')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping_site.categorycurrency', verbose_name='Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расход пользователя',
                'verbose_name_plural': 'Расходы пользователей',
            },
        ),
    ]
