# Generated by Django 4.2.4 on 2023-09-02 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping_site', '0003_categorycurrency_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping_site.categoryaccounts', unique=True, verbose_name='Cчета'),
        ),
    ]
