# Generated by Django 4.2.4 on 2023-09-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping_site', '0004_rename_categoryaccounts_categoriesaccounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesexpenses',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='categoriesincomes',
            name='parent',
        ),
        migrations.AddField(
            model_name='categoriesexpenses',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping_site.categoriesexpenses', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='categoriesincomes',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping_site.categoriesincomes', verbose_name='Категория'),
        ),
    ]
