# Generated by Django 4.2.4 on 2023-08-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping_site', '0004_categorycurrency_alter_categoryaccounts_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpenses',
            name='parent',
            field=models.CharField(default=1, verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
