# Generated by Django 4.2.4 on 2023-09-26 19:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookkeeping_site', '0005_remove_categoriesexpenses_parent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='UserAccounts',
        ),
    ]
