# Generated by Django 4.2.4 on 2023-09-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping_site', '0005_alter_useraccount_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransfertoaccount',
            name='course',
        ),
    ]
