# Generated by Django 4.2.4 on 2023-09-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping_site', '0006_rename_useraccount_useraccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransfertoaccount',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping_site.categoriescurrencys', verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriesaccounts',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='categoriescurrencys',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Название категории валюты'),
        ),
        migrations.AlterField(
            model_name='categoriesexpenses',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Название категории расхода'),
        ),
        migrations.AlterField(
            model_name='categoriesincomes',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Название категории дохода'),
        ),
    ]
