# Generated by Django 4.2.4 on 2023-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping_site', '0007_remove_userexpenses_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название категории счета')),
            ],
            options={
                'verbose_name': 'Категория Счета',
                'verbose_name_plural': 'Категории Счетов',
            },
        ),
        migrations.CreateModel(
            name='CategoryCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название категории валюты')),
            ],
            options={
                'verbose_name': 'Категория Валюты',
                'verbose_name_plural': 'Категории Валют',
            },
        ),
    ]
